### ISSUE TITLE
[Question] Changing error-handling

### ISSUE THREAD

**Issue by TornaxO7** [Roughsketch/nds#2]
Hello! I have a little question/suggestion here: When I was looking through your code, I saw that you used the [`failure`](https://crates.io/crates/failure) crate for error-handling. What do you think about [`error_chain`](https://crates.io/crates/error-chain)? `failure` seems to be [deprecated](https://github.com/rust-lang-nursery/failure#failure---a-new-error-management-story), do you agree, to change the error-handling by using `error_chain`?

**Comment by TornaxO7** [comment]
I'll post a pull-request soon (if it's fine for you).

**Comment by TornaxO7** [comment]
Or any other error-handling crate.

**Comment by Roughsketch** [comment]
I have heard of [anyhow](https://docs.rs/anyhow/1.0.42/anyhow/), but I haven't tried it out yet. I'll take a look at any PRs when I have some free time. Thanks for taking an interest!

**Comment by Roughsketch** [comment]
Closing since #3 was merged.
