### ISSUE TITLE
Explanation of NitroROM file system

### ISSUE THREAD

**Issue by TornaxO7** [Roughsketch/nds#7]
So I'm reading through your `nitro_fs` currently but I don't really understand what `overlays` does. Do you have some links for me where to read more about it?

PS: I know that your time is limited currently. I don't want to put you under more pressure! You can do that whenever you've got enough free time! :)

**Comment by Roughsketch** [comment]
When I was creating this my goal was to just get everything unpacked and packed correctly, so I never dived super deep into what exactly they are. They seem to just be files that exist in ROMs. However after googling it, it seems like they're pointer maps to memory addresses maybe? Can't say for sure and don't have the ability to test that out currently.

Here are some links you can go over:
[ARM documentation on overlays](https://developer.arm.com/documentation/100748/0613/overlays/overlay-support-in-arm-compiler)
[A thread going over usage of overlays](https://gbatemp.net/threads/pointer-tables.185458/)

**Comment by TornaxO7** [comment]
Thank you!
